### ISSUE TITLE
[Localization] 汉字 in create/update email job dialog

### ISSUE THREAD

**Issue by wudippda** [wudippda/jiazhou#7]
<img width="677" alt="screen shot 2018-11-04 at 9 03 53 pm" src="https://user-images.githubusercontent.com/7720794/47964451-56fcbe80-e075-11e8-8f2c-97a379e242ff.png">

As the picture shows,
1. the button text is Submit rather than "提交"。
2. the job type is still in its English name, any chance to display it in "计划任务，即时任务，延迟任务"？

Best regards,
Francis Zhong

**Comment by Hjyheart** [comment]
Fix that
