### ISSUE TITLE
[Localization] Improper translation for "next_time" attribute for email_job

### ISSUE THREAD

**Issue by wudippda** [wudippda/jiazhou#8]
<img width="569" alt="screen shot 2018-11-04 at 9 08 00 pm" src="https://user-images.githubusercontent.com/7720794/47964496-e5714000-e075-11e8-9271-d801fc955b11.png">

As the picture shows, 
1. Please change the name for "next_time" to “下次预计执行时间”. 
2. Another thing is, can we make the time value a little bit clearer? Currently it is like "2018-11-04T12:51:00.000Z", can we just keep it like "2018-11-04, 12:51:00"?

Best regards,
Francis Zhong

**Comment by Hjyheart** [comment]
Fix that
