### ISSUE TITLE
[Enhancement] Please provide meaningful message when delete/create email_job fails

### ISSUE THREAD

**Issue by wudippda** [wudippda/jiazhou#9]
<img width="1089" alt="screen shot 2018-11-04 at 9 14 32 pm" src="https://user-images.githubusercontent.com/7720794/47964548-a98aaa80-e076-11e8-8326-66e0ce7faa37.png">

As the picture shows, I am actually trying to delete a "scheduled" job, as job can only be deleted when it is "idle", the deletion should be failed. The above error message should tell user to stop the job first before deletion.

Best regards,
Francis Zhong

**Comment by Hjyheart** [comment]
Fix that
